version: '3.8'

services:
  db:
   
    image: postgres:16-alpine 
    

    container_name: postgres_recettes
    
  
    environment:
      
      POSTGRES_DB: recettes_maroc_db    
      
      POSTGRES_USER: votre_utilisateur_postgres 
      
      POSTGRES_PASSWORD: votre_mot_de_passe      
    
   
    ports:
      - "5432:5432" # le conetenur de posgressql est accessible via le port 
    
   
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: