version: '3.8'

services:
  # 1. Conteneur MySQL (moderne et compatible)
  mysql_recettes:
    image: mysql:8.0
    container_name: mysql_recettes
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'recettes_maroc_mysql_db' 
      MYSQL_USER: 'votre_utilisateur_mysql' 
      MYSQL_PASSWORD: 'votre_mot_de_passe_mysql'
      MYSQL_ROOT_PASSWORD: 'mot_de_passe_root_securise'
    ports:
      # Hôte 3308 -> Conteneur 3306 (évite XAMPP 3307)
      - "3308:3306"
    volumes:
      - db_data_mysql:/var/lib/mysql

  # 2. Conteneur phpMyAdmin
  phpmyadmin_recettes:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_recettes
    restart: always
    depends_on:
      - mysql_recettes
    ports:
      - 8081:80 # Accès à http://localhost:8081
    environment:
      PMA_HOST: mysql_recettes 
      # CORRECTION : Le port interne du conteneur MySQL est TOUJOURS 3306
      PMA_PORT: 3306 
      PMA_USER: root
      PMA_PASSWORD: mot_de_passe_root_securise

volumes:
  db_data_mysql: