version: '3.8'
services:

  # 1. Conteneur MySQL
  mysql_recettes:
    image: mysql:8.0
    container_name: mysql_recettes
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: recettes_maroc_mysql_db
      MYSQL_USER: django_user        # Utilisateur pour Django
      MYSQL_PASSWORD: django_pass    # Mot de passe pour Django
      MYSQL_ROOT_PASSWORD: mot_de_passe_root_securise
    ports:
      - "3308:3306"  # Hôte 3308 -> Conteneur 3306
    volumes:
      - db_data_mysql:/var/lib/mysql

  # 2. Conteneur phpMyAdmin
  phpmyadmin_recettes:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_recettes
    restart: always
    depends_on:
      - mysql_recettes
    ports:
      - "8081:80"  # Accès via http://localhost:8081
    environment:
      PMA_HOST: mysql_recettes
      PMA_PORT: 3306
      PMA_USER: root                   # Utilisateur root pour phpMyAdmin
      PMA_PASSWORD: mot_de_passe_root_securise

volumes:
  db_data_mysql:
